const wordArray = [
  "Because they make up everything!",
  "It's a shame they'll never meet.",
  "but now I use my hands.",
  "He'll stop at nothing to avoid them.",
  "Because he was outstanding in his field!",
  "I see food and I eat it!",
  "You planet!",
  "A gummy bear!",
  "Because they're always up to something.",
  "They’re never under any pressure to meet.",
  "Because it was two-tired.",
  "They woke up!",
  "She seemed surprised.",
  "Because they're shellfish!",
  "In case he got a hole in one!",
  "He just needed a little space.",
  "Climb a tree and act like a nut!",
  "Because it saw the salad dressing!",
  "It had too many problems.",
  "but I couldn't make enough dough.",
  "Frostbite!",
  "They don't have the guts!",
  "It's impossible to put down!",
  "You planet!",
  "Because it had too many problems.",
];

export default wordArray;
